### ISSUE TITLE
agregar nuevas imagenes a la carpeta product

### ISSUE THREAD

**Issue by ivanbecerrq** [esteban2oo1/software_de_tapiceria#55]
Plantilla de Historial de Usuario

Usuario : colaborador
nombre Usuario :ivanbecerrq

Título :agregar nuevas imagenes a la carpeta product
Puntos estimados a cambiar:1
Iteración aceptada 👍 :1

Descripción : restableci el codigo que borre en el anterior PR para pones las nuevas imagenes

**Comment by jessica123c** [comment]
bien
